Algoritmo "reajuste"
Var
cargo: inteiro
salario, reajuste, aumento: real
Inicio
Escreva ("Digite a cargo:")
Leia (cargo)
Escreva ("Digite a salario:")
Leia (salario)
Se (cargo = 1) entao
Escreva ("Codigo do cargo:", cargo)
Escreva ("Servicos gerais")
aumento<- salario*(50/100)
reajuste<- salario+aumento
Escreva ("O aumento e de:", aumento)
Escreva ("O novo salario e:", reajuste)
Senao
Se (cargo = 2) entao
Escreva ("Digite a cargo:", cargo)
aumento © salario*(30/100)
reajuste © salario+aumento
Escreva ("O aumento e de:", aumento)
Escreva ("O novo salario e:", reajuste)
Senao
Se (cargo = 3) entao
Escreva ("Digite a cargo:", cargo)
Escreva ("Vigia")
aumento © salario*(25/100)
reajuste © salario+aumento
Escreva ("O aumento e de:", aumento)
Escreva ("O novo salario e:", reajuste)
Senao
Se (cargo = 3) entao
Escreva ("Digite a cargo:", cargo)
Escreva ("Vigia")
aumento<- salario*(15/100)
reajuste<- salario+aumento
Escreva ("O aumento e de:", aumento)
Escreva ("O novo salario e:", reajuste)
Fimse
Fimse
Fimse
Fimse
Fimalgoritmo
